import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "./context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jsonLd: WithContext<VideoGame> = {
  '@context': 'https://schema.org',
  '@type': 'VideoGame',
  name: 'Friends and Fables',
  description:
    'Play an AI text adventure RPG inspired by DnD (Dungeons and Dragons). Dungeon masters love our AI dungeon, character, and world building tools. Explore infinite worlds with our AI Game Master today!',
  playMode: 'MultiPlayer',
  gamePlatform: 'Web Browser',
  applicationCategory: 'Game',
  genre: ['Role Playing Game', 'Fantasy', 'Adventure', 'Dungeons & Dragons'],
  gameItem: ['Characters', 'Spells', 'Items', 'Dungeons'],
  publisher: {
    '@type': 'Organization',
    name: 'Sidequest Labs',
  } as Organization,
  author: [
    {
      '@type': 'Person',
      name: 'Will Liu',
    } as Person,
    {
      '@type': 'Person',
      name: 'David Melnychuk',
    } as Person,
  ],
  url: 'https://fables.gg',
  offers: {
    '@type': 'Offer',
    category: 'Online Gaming',
    availability: 'https://schema.org/OnlineOnly',
  },
  audience: {
    '@type': 'PeopleAudience',
    suggestedMinAge: '18',
  },
};

export const metadata: Metadata = {
  title: 'AI Game Master for DnD inspired text adventure RPGs',
  description:
    'Play an AI text adventure RPG inspired by DnD (Dungeons and Dragons). Dungeon masters love our AI dungeon, character, and world building tools. Explore infinite worlds with our AI Game Master today!',
  applicationName: 'Friends and Fables',
  keywords: [
    'Friends & Fables',
    'Friends and Fables',
    'Franz',
    'AI RPG',
    'AI DnD',
    'AI DnD',
    'AI TTRPG',
    'AI Dungeon Master',
    'AI Game Master',
    'AI Dungeons & Dragons',
    'AI Dungeon',
    'AI TTRPG',
    'TTRPG',
    'World Building',
    'WorldBuilding',
    'D20',
    '5e',
  ],
  creator: 'Will Liu and David Melnychuk',
  authors: [
    {
      name: 'Will Liu',
    },
    {
      name: 'David Melnychuk',
    },
  ],
  publisher: 'Sidequest Labs',
  metadataBase: new URL('https://fables.gg'),
  openGraph: {
    title: 'AI Game Master for DnD inspired text adventure RPGs',
    description:
      'Play an AI text adventure RPG inspired by DnD (Dungeons and Dragons). Dungeon masters love our AI dungeon, character, and world building tools. Explore infinite worlds with our AI Game Master today!',
    url: 'https://fables.gg',
    siteName: 'Friends & Fables',
    locale: 'en_US',
    type: 'website',
  },
  alternates: {
    canonical: '/',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
